# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hey < Formula
  desc "A templating tool using helm flavoured sprig"
  homepage "https://github.com/rjshrjndrn/hey"
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.5/hey_0.1.5_darwin_amd64.tar.gz"
      sha256 "30fb39ab1f9855a7789cacde33631902a313728b4dae64efe1be6267dc466447"

      def install
        bin.install "hey"
      end
    end
    on_arm do
      url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.5/hey_0.1.5_darwin_arm64.tar.gz"
      sha256 "81eb28c966730d259588738552dc51fa6cbcde92fb20a8ee1a3d18e44a131f10"

      def install
        bin.install "hey"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.5/hey_0.1.5_linux_amd64.tar.gz"
        sha256 "d50af86e9117495d7817db31664e0f168dd879778aa4984c944a8ce631b055cd"

        def install
          bin.install "hey"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.5/hey_0.1.5_linux_arm64.tar.gz"
        sha256 "63e582c412140d797c08fe75f9c0527a7f4428c33f710ce6be84cf41d849f4eb"

        def install
          bin.install "hey"
        end
      end
    end
  end

  test do
    system "#{bin}/hey --version"
  end
end
