# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hey < Formula
  desc "A templating tool using helm flavoured sprig"
  homepage "https://github.com/rjshrjndrn/hey"
  version "0.1.6"

  on_macos do
    on_intel do
      url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.6/hey_0.1.6_darwin_amd64.tar.gz"
      sha256 "36c3fff3640270b947a19f401726c8f2cab79644aaaf53dafd38d891ca3bb6cb"

      def install
        bin.install "hey"
      end
    end
    on_arm do
      url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.6/hey_0.1.6_darwin_arm64.tar.gz"
      sha256 "e1dc2fe79a1c643e0368877be2ee4ac02a2900e686c26082803222859056929c"

      def install
        bin.install "hey"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.6/hey_0.1.6_linux_amd64.tar.gz"
        sha256 "f16ba4f36e9971b9ad9f6eb58fe3f83f9b2ca4ed83535c3e57ac450eee53f3b2"

        def install
          bin.install "hey"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.6/hey_0.1.6_linux_arm64.tar.gz"
        sha256 "8b6c5f064ffd2a323e44c9cd581c39b1c6301e15796ed939689c4c242238a684"

        def install
          bin.install "hey"
        end
      end
    end
  end

  test do
    system "#{bin}/hey --version"
  end
end
