# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hey < Formula
  desc "A templating tool using helm flavoured sprig"
  homepage "https://github.com/rjshrjndrn/hey"
  version "0.1.6"

  on_macos do
    on_intel do
      url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.6/hey_0.1.6_darwin_amd64.tar.gz"
      sha256 "fc2d7e5ccbede070752945d624a79003235b27ea81c2b18011aa5a7f1a5ce416"

      def install
        bin.install "hey"
      end
    end
    on_arm do
      url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.6/hey_0.1.6_darwin_arm64.tar.gz"
      sha256 "704a5613e07e5088a9d1107acd5e17a4b42a371fd5efbe184bd47688f62aa82d"

      def install
        bin.install "hey"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.6/hey_0.1.6_linux_amd64.tar.gz"
        sha256 "33c4fa41513f4c457363a68613a7b2b5b9cf98213f8a8296811f47745590ebd1"

        def install
          bin.install "hey"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjshrjndrn/hey/releases/download/v0.1.6/hey_0.1.6_linux_arm64.tar.gz"
        sha256 "723c7383213c69ea758417e2c6473acf08b52f4886bf930244424f718a871b67"

        def install
          bin.install "hey"
        end
      end
    end
  end

  test do
    system "#{bin}/hey --version"
  end
end
