# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Templater < Formula
  desc "A templating tool using helm flavoured sprig"
  homepage "https://github.com/rjshrjndrn/templater"
  version "6.2.3"

  on_macos do
    on_intel do
      url "https://github.com/rjshrjndrn/templater/releases/download/v6.2.3/templater_6.2.3_darwin_amd64.tar.gz"
      sha256 "ee1fe957e5608c1c4655c28424730838db3a0f9eb6679e571b78105976cf0c49"

      def install
        bin.install "templater"
      end
    end
    on_arm do
      url "https://github.com/rjshrjndrn/templater/releases/download/v6.2.3/templater_6.2.3_darwin_arm64.tar.gz"
      sha256 "e87ca6ff2285e90cf5034dca305adda4c881c63a282a7cacd85563f39fc90504"

      def install
        bin.install "templater"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjshrjndrn/templater/releases/download/v6.2.3/templater_6.2.3_linux_amd64.tar.gz"
        sha256 "c8b528b333eb75bfe696484a486cfe75fbb7e1a111f77371474df4acec88554a"

        def install
          bin.install "templater"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjshrjndrn/templater/releases/download/v6.2.3/templater_6.2.3_linux_arm64.tar.gz"
        sha256 "4e0146405cdba6c2f89d10d5ccaee86144c0a559f4697009309968a1278caa8b"

        def install
          bin.install "templater"
        end
      end
    end
  end

  test do
    system "#{bin}/templater --version"
  end
end
