# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Templater < Formula
  desc "A templating tool using helm flavoured sprig"
  homepage "https://github.com/rjshrjndrn/templater"
  version "6.1.0"

  on_macos do
    on_intel do
      url "https://github.com/rjshrjndrn/templater/releases/download/v6.1.0/templater_6.1.0_darwin_amd64.tar.gz"
      sha256 "597c218ec494bb0000390ad0380b5d9c663466d3d1ea466e28dd20c476cd491b"

      def install
        bin.install "templater"
      end
    end
    on_arm do
      url "https://github.com/rjshrjndrn/templater/releases/download/v6.1.0/templater_6.1.0_darwin_arm64.tar.gz"
      sha256 "8fad50765b2ed8b0040bd66aacd67f5461f06ed756491ed274d260634daac62e"

      def install
        bin.install "templater"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjshrjndrn/templater/releases/download/v6.1.0/templater_6.1.0_linux_amd64.tar.gz"
        sha256 "10c94c2fb615a94a9f4b62575441bcd34ff987279e051b8e72f0141ea8e134b2"

        def install
          bin.install "templater"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjshrjndrn/templater/releases/download/v6.1.0/templater_6.1.0_linux_arm64.tar.gz"
        sha256 "ef7a1b0e09b51a7371a2d90536ee8b2e7451963b80511d1775d21735751e6009"

        def install
          bin.install "templater"
        end
      end
    end
  end

  test do
    system "#{bin}/templater --version"
  end
end
